### ISSUE TITLE
some of the hide block settings are mixed up

### ISSUE THREAD

**Issue by Scythe17** [Hao-1337/mindustry-better-vanilla#3]
in the [ Better Vanilla ] settings the option to hide the Silo will instead hide the Box and the option to hide the Box will instead hide the Silo, the options for hiding the thorium and surge conveyors are also reversed, additionally the option to hide the leviathan constructor does nothing at all regardless of whether it's on or off

in case it matters I'm playing the game on an Android Chromebook

**Comment by Hao-1337** [comment]
Alright might be i just messing arround so. The original idea was to turn it off when you're in multiplayer but Anuke don't let me do it. I'll probably remove it or make only one toggle, what do you think?
